- Media:
  - Plex:
      icon: plex.png
      href: http://192.168.50.50:32400/web
      siteMonitor: http://192.168.50.50:32400
      description: Plex media server.

  - Jellyfin:
      icon: jellyfin.png
      href: http://192.168.50.50:8096
      siteMonitor: http://192.168.50.50:8096
      description: Jellyfin media server.

  - Audiobookshelf:
      icon: audiobookshelf.png
      href: https://audiobookshelf.lanjian.io
      siteMonitor: https://audiobookshelf.lanjian.io
      description: Audiobook and podcast media server.

- Requesters:
  - Jellyseerr:
      icon: jellyseerr.png
      href: https://jellyseerr.lanjian.io
      siteMonitor: https://jellyseerr.lanjian.io
      description: Media requests.

  - Radarr:
      icon: radarr.png
      href: https://radarr.lanjian.io
      siteMonitor: https://radarr.lanjian.io
      description: Movie requests.

  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.lanjian.io
      siteMonitor: https://sonarr.lanjian.io
      description: TV show requests.

  - Readarr:
      icon: readarr.png
      href: https://readarr.lanjian.io
      siteMonitor: https://readarr.lanjian.io
      description: Book requests.

  - Audiobookrequest:
      icon: https://raw.githubusercontent.com/markbeep/AudioBookRequest/refs/heads/main/static/android-chrome-512x512.png
      href: https://audiobookrequest.lanjian.io
      siteMonitor: https://audiobookrequest.lanjian.io
      description: Audiobook requests.

  - Prowlarr:
      icon: prowlarr.png
      href: https://prowlarr.lanjian.io
      siteMonitor: https://prowlarr.lanjian.io
      description: Indexer management.

- Services:
  - tandoor:
      icon: tandoor-recipes.png
      href: https://tandoor.lanjian.io
      siteMonitor: https://tandoor.lanjian.io
      description: Recipe database and meal planning.

  - ntfy:
      icon: ntfy.png
      href: https://ntfy.lanjian.io
      siteMonitor: https://ntfy.lanjian.io
      description: Internal Pub/Sub notifications.

  - gitea:
      icon: gitea.png
      href: https://gitea.lanjian.io
      siteMonitor: https://gitea.lanjian.io
      description: Source control server and package registry.

  - Synology NAS:
      icon: synology-dsm.png
      href: http://speranza.local:5000
      description: Primary NAS.

- Download Clients:
  - SABnzbd:
      icon: sabnzbd.png
      href: https://sabnzbd.lanjian.io
      siteMonitor: https://sabnzbd.lanjian.io
      description: Usenet client.

  - MeTube:
      icon: metube.png
      href: https://metube.lanjian.io
      siteMonitor: https://metube.lanjian.io
      description: YouTube (and others) downloader.

- Cluster Tools:
  - pfSense:
      icon: pfsense.png
      href: https://192.168.50.1
      siteMonitor: https://192.168.50.1
      description: pfSense admin console.

  - Omada Controller:
      icon: omada.png
      href: https://192.168.10.10
      siteMonitor: https://192.168.10.10
      description: Omada controller admin console.

  - Argo CD:
      icon: argo-cd.png
      href: https://argocd.lanjian.io
      siteMonitor: https://argocd.lanjian.io
      description: GitOps deploys for kubernetes cluster.

  - traefik-internal:
      icon: traefik.png
      href: http://traefik.lanjian.io
      siteMonitor: http://traefik.lanjian.io
      description: Internal reverse proxy routing dashboard.

  - tailscale:
      icon: tailscale.png
      href: https://login.tailscale.com/admin
      description: VPN service.
