---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "bazarr"
namePrefix: "bazarr-"
images:
  - name: "linuxserver/bazarr"
    newTag: "1.5.4"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
